apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fhirbotwebui
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fhirbotwebui
    spec:
      containers:
      - name: fhirbotwebui
        image: stodocker/fhirbotwebui:latest
        ports:
            - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  name: fhirbotwebui-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: fhirbotwebui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer